name: Pull Request

on:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      scopes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            all:
              - 'go.mod'
              - 'go.sum'
              - 'coremodule/**'
            stringmodule:
              - 'stringmodule/**'
            mathmodule:
              - 'mathmodule/**'

  all-test:
    needs: changes
    if: ${{ contains(needs.changes.outputs.scopes, 'all') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test -v ./...

  module-tests:
    needs: changes
    if: |
      !contains(needs.changes.outputs.scopes, 'all') &&
      (
        contains(needs.changes.outputs.scopes, 'stringmodule') ||
        contains(needs.changes.outputs.scopes, 'mathmodule')
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [stringmodule, mathmodule]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run tests for ${{ matrix.module }}
        run: cd ${{ matrix.module }} && go test -v ./...
